### ISSUE TITLE
Unable to find image

### ISSUE THREAD

**Issue by ashukw** [rithinskaria/kodekloud#1]
Script is failing to create V with given image, however Ubuntu2204 is working

New-AzVM: /home/odl_user/azure-lab.ps1:26
Line |
  26 |  New-AzVM -Name "vm-0a" `
     |  ~~~~~~~~~~~~~~~~~~~~~~~~
     | Can't find the image 'UbuntuLTS'.

**Comment by rithinskaria** [comment]
UbuntuLTS alias is deprecated. You need to use Ubuntu2204

This will be updated in the course refresh which is scheduled to launch in January.

Eg:

New-AzVM -Name "spoke-a-vm-$i" `
        -ResourceGroupName $rg `
        -Location eastus `
        -Size 'Standard_B1s' `
        -Image "Ubuntu2204" `
        -VirtualNetworkName "spoke-a" `
        -SubnetName 'default' `
        -Credential $credential `
        -PublicIpAddressName "spoke-a-vm-$i-pip" `
        -PublicIpSku Standard

If you are setting image version, it will be:

Set-AzVMSourceImage -VM $VirtualMachine `
            -PublisherName 'Canonical' `
            -Offer '0001-com-ubuntu-server-jammy' `
            -Skus '22_04-lts-gen2' `
            -Version latest



________________________________
From: ashukw ***@***.***>
Sent: Wednesday, November 15, 2023 10:23 AM
To: rithinskaria/kodekloud ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [rithinskaria/kodekloud] Unable to find image (Issue #1)


Script is failing to create V with given image, however Ubuntu2204 is working

New-AzVM: /home/odl_user/azure-lab.ps1:26
Line |
26 | New-AzVM -Name "vm-0a" `
| ~~~~~~~~~~~~~~~~~~~~~~~~
| Can't find the image 'UbuntuLTS'.
